// Generated by scripts/build-rexonance-suit.mjs from
// design/rexonance-suit/rexonance-full-20261010.jpg — do not edit by hand.
// Figure coordinates are delivery pixels of the 566 x 1040 figure.
// 26 files, 527254 bytes.

export const REXONANCE_SUIT_SIZE = { width: 566, height: 1040 } as const;

/** The finished figure (the still tiers and the fallback). */
export const REXONANCE_SUIT_FIGURE = "/rexonance-suit-20261010/figure.webp";
/** The bare bodysuit the armour lands on. */
export const REXONANCE_SUIT_UNDERSUIT = "/rexonance-suit-20261010/undersuit.webp";

export type RexonanceSuitLayer = {
  readonly src: string;
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
};
/** The bodysuit between the plates, as painted. */
export const REXONANCE_SUIT_BODY: RexonanceSuitLayer = {
  src: "/rexonance-suit-20261010/body.webp",
  x: 84,
  y: 11,
  w: 427,
  h: 1025,
};
/** The face's cyan and pink lights, lit. */
export const REXONANCE_SUIT_FACE: RexonanceSuitLayer = {
  src: "/rexonance-suit-20261010/face.webp",
  x: 237,
  y: 105,
  w: 91,
  h: 94,
};
/** The lights' outline, for the final call's pixel squares. */
export const REXONANCE_SUIT_FACE_GLOW: readonly (readonly [number, number])[] = [
  [240.4, 109.4],
  [250.4, 111.1],
  [260.4, 121.6],
  [270.4, 135.5],
  [280.4, 146.6],
  [291, 135.5],
  [301.5, 122.2],
  [312.6, 111.1],
  [323.7, 108.8],
  [318.2, 123.3],
  [308.2, 138.3],
  [298.2, 152.1],
  [289.3, 166],
  [284.3, 179.9],
  [281.5, 195.5],
  [278.2, 179.9],
  [272.6, 166],
  [263.7, 152.1],
  [253.8, 138.3],
  [246, 124.4],
];

export type RexonanceSuitGroup = "legs" | "arms" | "chest" | "waist" | "tail" | "ribbon" | "helm";
export type RexonanceSuitPiece = RexonanceSuitLayer & {
  readonly id: string;
  readonly group: RexonanceSuitGroup;
  /** Where its clank sparks (a seam). */
  readonly seat: readonly [number, number];
  /** The hover it forms in: [dx, dy] in figure heights, a turn (deg), a scale. */
  readonly float?: readonly [number, number, number, number];
};
/** Each piece's sprite holds three panels: art, nanite mosaic, rim. Front first. */
export const REXONANCE_SUIT_PIECES: readonly RexonanceSuitPiece[] = [
  {
    id: "helmet",
    group: "helm",
    src: "/rexonance-suit-20261010/helmet.webp",
    x: 207,
    y: 0,
    w: 142,
    h: 225,
    seat: [282.1, 204.9],
    float: [0, -0.085, 0, 1.06],
  },
  {
    id: "core",
    group: "chest",
    src: "/rexonance-suit-20261010/core.webp",
    x: 215,
    y: 208,
    w: 134,
    h: 158,
    seat: [282.1, 224.3],
    float: [0, -0.012, -8, 1.14],
  },
  {
    id: "belt",
    group: "waist",
    src: "/rexonance-suit-20261010/belt.webp",
    x: 159,
    y: 370,
    w: 246,
    h: 102,
    seat: [282.1, 388.1],
    float: [0, 0.01, 0, 1.1],
  },
  {
    id: "tasset",
    group: "waist",
    src: "/rexonance-suit-20261010/tasset.webp",
    x: 233,
    y: 435,
    w: 98,
    h: 372,
    seat: [282.1, 452],
    float: [0, 0.03, 0, 1.06],
  },
  {
    id: "shoulder-l",
    group: "chest",
    src: "/rexonance-suit-20261010/shoulder-l.webp",
    x: 35,
    y: 89,
    w: 229,
    h: 297,
    seat: [222.7, 229.9],
    float: [-0.06, -0.045, -5, 1.04],
  },
  {
    id: "shoulder-r",
    group: "chest",
    src: "/rexonance-suit-20261010/shoulder-r.webp",
    x: 300,
    y: 111,
    w: 193,
    h: 275,
    seat: [341.5, 229.9],
    float: [0.06, -0.045, 5, 1.04],
  },
  {
    id: "gauntlet-l",
    group: "arms",
    src: "/rexonance-suit-20261010/gauntlet-l.webp",
    x: 46,
    y: 323,
    w: 130,
    h: 282,
    seat: [134.9, 350.9],
    float: [-0.07, 0.012, -6, 1.03],
  },
  {
    id: "gauntlet-r",
    group: "arms",
    src: "/rexonance-suit-20261010/gauntlet-r.webp",
    x: 388,
    y: 322,
    w: 130,
    h: 283,
    seat: [429.2, 350.9],
    float: [0.07, 0.012, 6, 1.03],
  },
  {
    id: "chest",
    group: "chest",
    src: "/rexonance-suit-20261010/chest.webp",
    x: 194,
    y: 186,
    w: 177,
    h: 219,
    seat: [282.1, 388.1],
    float: [0, -0.02, 0, 1.08],
  },
  {
    id: "thigh-l",
    group: "waist",
    src: "/rexonance-suit-20261010/thigh-l.webp",
    x: 131,
    y: 434,
    w: 137,
    h: 217,
    seat: [200.4, 449.8],
    float: [-0.05, 0.03, -4, 1.04],
  },
  {
    id: "thigh-r",
    group: "waist",
    src: "/rexonance-suit-20261010/thigh-r.webp",
    x: 297,
    y: 434,
    w: 137,
    h: 217,
    seat: [363.7, 449.8],
    float: [0.05, 0.03, 4, 1.04],
  },
  {
    id: "knee-l",
    group: "legs",
    src: "/rexonance-suit-20261010/knee-l.webp",
    x: 101,
    y: 610,
    w: 155,
    h: 198,
    seat: [183.8, 626.9],
    float: [-0.06, 0.02, -5, 1.04],
  },
  {
    id: "knee-r",
    group: "legs",
    src: "/rexonance-suit-20261010/knee-r.webp",
    x: 306,
    y: 610,
    w: 156,
    h: 199,
    seat: [380.4, 626.9],
    float: [0.06, 0.02, 5, 1.04],
  },
  {
    id: "boot-l",
    group: "legs",
    src: "/rexonance-suit-20261010/boot-l.webp",
    x: 64,
    y: 747,
    w: 179,
    h: 293,
    seat: [156, 774],
    float: [-0.055, 0.045, -4, 1.03],
  },
  {
    id: "boot-r",
    group: "legs",
    src: "/rexonance-suit-20261010/boot-r.webp",
    x: 322,
    y: 745,
    w: 178,
    h: 295,
    seat: [408.1, 774],
    float: [0.055, 0.045, 4, 1.03],
  },
  {
    id: "tail-0",
    group: "tail",
    src: "/rexonance-suit-20261010/tail-0.webp",
    x: 318,
    y: 93,
    w: 76,
    h: 67,
    seat: [350.4, 168.8],
  },
  {
    id: "tail-1",
    group: "tail",
    src: "/rexonance-suit-20261010/tail-1.webp",
    x: 319,
    y: 0,
    w: 117,
    h: 122,
    seat: [353.1, 108.8],
  },
  {
    id: "tail-2",
    group: "tail",
    src: "/rexonance-suit-20261010/tail-2.webp",
    x: 396,
    y: 0,
    w: 127,
    h: 118,
    seat: [408.7, 30],
  },
  {
    id: "tail-3",
    group: "tail",
    src: "/rexonance-suit-20261010/tail-3.webp",
    x: 478,
    y: 24,
    w: 88,
    h: 136,
    seat: [500.3, 35.5],
  },
  {
    id: "tail-4",
    group: "tail",
    src: "/rexonance-suit-20261010/tail-4.webp",
    x: 455,
    y: 132,
    w: 111,
    h: 196,
    seat: [530.8, 146.6],
  },
  {
    id: "ribbon-l",
    group: "ribbon",
    src: "/rexonance-suit-20261010/ribbon-l.webp",
    x: 0,
    y: 309,
    w: 172,
    h: 569,
    seat: [67.2, 313.2],
  },
  {
    id: "ribbon-r",
    group: "ribbon",
    src: "/rexonance-suit-20261010/ribbon-r.webp",
    x: 397,
    y: 284,
    w: 163,
    h: 598,
    seat: [444.8, 313.2],
  },
];

export const REXONANCE_SUIT_MARKS = {
  core: [282.1, 275.4],
  visor: [282.1, 146.6],
  belt: [282.1, 421.4],
  joints: [
    [282.1, 275.4],
    [172.7, 236.5],
    [391.5, 236.5],
    [116, 379.8],
    [448.1, 379.8],
    [183.8, 696.3],
    [380.4, 696.3],
  ],
} as const;

/** Every file the suit-up paints, for the warm-up. */
export const REXONANCE_SUIT_ASSETS = [
  REXONANCE_SUIT_UNDERSUIT,
  ...REXONANCE_SUIT_PIECES.map((piece) => piece.src),
  REXONANCE_SUIT_BODY.src,
  REXONANCE_SUIT_FACE.src,
] as const;
