// Generated by scripts/build-search-form-index.mjs from
// public/{saga,realm}-form-archive-embedded.html. Do not edit by hand.
export type ArchiveForm = {
  id: string;
  archive: "saga" | "realm";
  name: string;
  tier: string;
};

export const FORM_ARCHIVE_FORMS: readonly ArchiveForm[] = [
  { id: "multi", archive: "saga", name: "マルチフォーム", tier: "通常｜万能・近接基盤" },
  {
    id: "last-multi",
    archive: "saga",
    name: "ラストマルチ",
    tier: "限界解放｜最終必殺・全性能解放",
  },
  { id: "flam", archive: "saga", name: "フラムフォーム", tier: "並列｜遠距離・市街地・撹乱" },
  { id: "aero", archive: "saga", name: "エアロフォーム", tier: "並列｜空中機動・射撃" },
  { id: "rock", archive: "saga", name: "ロックフォーム", tier: "並列｜近接・防御" },
  { id: "hybrid", archive: "saga", name: "ハイブリッドフォーム", tier: "強化｜融和・一点貫通" },
  {
    id: "full-custom",
    archive: "saga",
    name: "ハイブリッドフォーム フルカスタム",
    tier: "強化｜範囲拡張・総合戦闘",
  },
  { id: "integral", archive: "saga", name: "インテグラルサーガ", tier: "最強｜近接極限・上昇出力" },
  { id: "vertex", archive: "saga", name: "ヴァーテックスサーガ", tier: "最強｜高速演算・中遠距離" },
  { id: "diluculum", archive: "saga", name: "ディルクルムサーガ", tier: "究極｜拒絶・悪夢浄化" },
  { id: "vinculum", archive: "saga", name: "ヴィンクルムサーガ", tier: "究極｜接続・統合・多次元" },
  {
    id: "last-vinculum",
    archive: "saga",
    name: "ラストヴィンクルム",
    tier: "究極・限界解放｜ヴィンクルムの出力上昇",
  },
  {
    id: "extreme",
    archive: "saga",
    name: "エクスプリームサーガ",
    tier: "究極｜結果確定・対管理人",
  },
  {
    id: "extreme-ultra",
    archive: "saga",
    name: "エクスプリームサーガ ウルトラ",
    tier: "究極・一時強化｜エクスプリームの最高出力",
  },
  {
    id: "rexonance",
    archive: "saga",
    name: "レクソナンスサーガ",
    tier: "超究極｜実在上位編集・神飾実装",
  },
  {
    id: "rexonance-max",
    archive: "saga",
    name: "レクソナンスサーガ マックス",
    tier: "超究極・60秒限定｜能力性能倍増・広域放出",
  },
  {
    id: "rexonance-ultra",
    archive: "saga",
    name: "レクソナンスサーガ ウルトラ",
    tier: "超究極・60秒限定｜一時高性能化・短期決着",
  },
  { id: "stella", archive: "realm", name: "ステラフォーム", tier: "01 / 基準｜明示設定" },
  { id: "burst", archive: "realm", name: "バーストフォーム", tier: "02 / 並列｜地上圧縮" },
  { id: "blast", archive: "realm", name: "ブラストフォーム", tier: "02 / 並列｜完全空戦" },
  { id: "legends", archive: "realm", name: "レルムレジェンズ", tier: "03 / 最強｜勝利証明" },
  { id: "royal", archive: "realm", name: "レルムロイヤル", tier: "04 / 究極｜王国宣言" },
  {
    id: "royal-wrath",
    archive: "realm",
    name: "レルムロイヤル・ラース",
    tier: "04 / 究極｜攻勢属性群",
  },
  {
    id: "royal-abyss",
    archive: "realm",
    name: "レルムロイヤル・アビス",
    tier: "04 / 究極｜深層属性群",
  },
  {
    id: "royal-birth",
    archive: "realm",
    name: "レルムロイヤル・バース",
    tier: "04 / 究極｜生成属性群",
  },
  {
    id: "royal-nehan",
    archive: "realm",
    name: "レルムロイヤル・ウルトラ",
    tier: "04 / 究極｜終端属性群",
  },
];
