import type { SearchDocument } from "./search-engine";
import { FORM_ARCHIVE_FORMS } from "./form-archive-index";
import { DANTE_FACTS, DANTE_FORMS, DANTE_SECTIONS } from "../world/dante-data";
import { RELATED_SECTIONS } from "../world/related-data";
import { YOAKE_MAMORI_SECTIONS } from "../world/yoake-mamori-data";
import { WORLD_COLUMNS } from "../world/world-columns-data";
import {
  WORLD_BRIEF,
  WORLD_CAST_ROSTER,
  WORLD_EPISODE_NOTES,
  WORLD_GLOSSARY,
  WORLD_LOCATIONS,
} from "../world/world-annex-data";
import {
  DREAM_CASES,
  DREAM_CAST_ROSTER,
  DREAM_CHARACTERS,
  DREAM_DOLMINENCE,
  DREAM_FACTIONS,
  DREAM_GLOSSARY,
} from "../dream-chapter/dream-chapter-data";
import { CAST, FAR_FROM_SAGA, REALM_ROYAL, STORY } from "../final-stage/final-stage-data";
import { LIBRARY_ENTRIES } from "../../lib/library-data";
import {
  SPECIAL_SITE_PATHS,
  SPECIAL_SITE_SECTIONS,
  SPECIAL_SITE_TITLES,
  type SpecialSiteId,
} from "../../lib/special-site-sections";

export const SEARCH_CATEGORIES = [
  { id: "all", label: "すべて", code: "ALL" },
  { id: "people", label: "人物", code: "PEOPLE" },
  { id: "riders", label: "ライダー", code: "RIDERS" },
  { id: "forms", label: "フォーム", code: "FORMS" },
  { id: "story", label: "物語", code: "STORY" },
  { id: "world", label: "世界・用語", code: "WORLD" },
  { id: "systems", label: "システム", code: "SYSTEMS" },
  { id: "pages", label: "ページ", code: "PAGES" },
] as const;

export type SearchCategory = (typeof SEARCH_CATEGORIES)[number]["id"];
export type SearchCatalogueDocument = SearchDocument;

// These small excerpts preserve the published dossiers without importing their UI,
// artwork, motion or modal dependencies into the search route. Source parity is
// checked by scripts/search-data.test.mjs. Pure content tables below stay live.
const DOSSIER_DOCUMENTS: readonly SearchCatalogueDocument[] = [
  {
    id: "manager-zeus",
    title: "ゼウス",
    category: "people",
    description: "主権を継いだ六詠第一位",
    body: "生まれながらに、第一位の名を継いだ神。\n『六詠』の一位に位置する、青年の姿をした『主権』の神。生まれて100年も経過していないが、秩序によって一位の後任に選ばれ、誕生とともに“ゼウス”の名を襲名した。本人はまだルーキーで、管理もあまり上手くない。\n気さくなまま、拒否する余地だけを消す。\n六詠第一位らしい強烈な自信と高圧性を持つ一方、実際の人柄は意外なほど気さく。敬語はほぼ使わず、年長者や他の管理人に対しても『お前』『君』『レックス』などと普通に呼び掛ける。これは相手を侮辱しているというより、そもそも上下関係を過剰に儀礼化する習慣が本人にないためである。\n自分が第一位であり、周囲より遥かに強いことについても隠さないが、それを何度も誇示するような性格ではない。『私の方が上なんだから黙って従え』と怒鳴るより、『私の方が上だろ。で、何か問題ある？』と記した方が近いだろう。\n面白そうなものには気軽に近寄り、知らない文化について質問し、人間の妙な習慣を見て笑うこともある。世界内部の食事や娯楽にも興味を持ち、管理任務の途中で寄り道することさえある。\nただし、第一位として判断を下す瞬間には空気が変わる。普段の気安さを残したまま、『駄目だ。それは通さない』の一言で全てを止める。声を低くする必要すらない。いつもの口調のまま、拒否する余地だけが消える。\nこの『親しみやすさ』と『逆らえない絶対性』が同居しているのが、ゼウス最大の特徴となる。\n管理人歴が数年しかなく、経験不足を自覚している。知ったかぶりをせずに教わるが、態度まで殊勝になるわけではない。頭の回転と学習能力は極めて高く、その成長には危険性も伴う。\n本人にとって未知のものほど興味深いため、人間の突拍子もない行動や、合理性を無視した友情、意地、善意などには強い好奇心を示す。",
    keywords: ["六詠", "I"],
    to: "/managers/zeus",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "生まれながらに、第一位の名を継いだ神。" },
      { no: "02", title: "気さくなまま、拒否する余地だけを消す。" },
    ],
  },
  {
    id: "manager-rex-loi",
    title: "レックス・ロワ",
    category: "people",
    description: "秩序の大口と裁定者の仮面",
    body: "世界を残し、支配だけを終わらせるために。\n固定された管轄を持たない六詠の管理人であり、『仮面ライダーノット』の世界を臨時で管理している。管理人達を監督する都護府のような立場から、本来なら複数の機関で分担する役割を単独で担う。率先して責任を引き受ける模範的な態度と、破壊者として猛々しく冷徹な判断を併せ持つ。\nサーガ世界の問題も自ら解決すべき事案と考えているが、その権能はローアの管理構造とともに、辛うじて維持される世界自体を破壊しかねない。誰よりも解放を望みながら自分の力だけでは実現できず、世界を残したまま管理構造だけを終わらせ得る存在を探し、他の六詠に先んじて暗躍する。\n他者の選択を奪わない、六詠唯一の完全なる良心。\n冷静沈着で慇懃かつ親切。相手の立場や能力を認めながらも自他を対等に捉え、静かな口調と寛容さを崩さない。善意や友情、使命感を軽んじるように振る舞うことはあっても、その力を正確に理解して尊重し、意図的に踏みにじることはない。\n戦闘を『儀式』と呼び、他者の選択を奪ってきた絶対者に、自らの誤りと敗北を理解させるために破壊を行う。その際にも人格や尊厳を弄ぶことはない。策略に長け、必要なら正面戦闘や敵対者との一時的な共闘も選び、第一位と同等の行動権を用いて事案の解決へ協力する。\n予測を外す存在は重要な観測対象とするが、脅威か救済の可能性かを見極めるまでは排除しない。提案の拒絶も当然の自衛として尊重し、不利益を与えることはなく、過去に協力を断った者からの救援にも真摯に応じる。\n敵の能力と逃走手段を見抜き、正面から圧倒する。\n卓越した身体能力による近接格闘を軸に、敵の能力、思考、関係性、戦闘履歴を解析する。逃走経路や反撃手段、能力の発動条件、精神的な支柱まで把握してなお正面から圧倒することを、支配の根拠を最も効率よく破壊する手段と考えている。戦闘開始直後には、あえて防御や回避を抑えて攻撃を観察する。\n光で現実へ定着させ、闇で外の干渉を遮る。\nブロンドの髪と人ならざる麗貌、豪奢な祭服を持つ青年の姿を取るが、人間ではない。人々の想いが集積して成立した『秩序の神』であり、通常の物理攻撃は通用せず、口内には鋭い毒牙を備える。神体の人型部分には光、蛇状の尾『秩序』には闇の神性が強く表れる。\n光は隠されたものを明らかにし、生命、意思、法則を現実へ定着させる力。闇は外部の干渉を遮って休息を与え、過剰な力や不要な構造を呑み込み、静寂へ還す力である。過剰な光は監視と支配に、過剰な闇は停滞と消失に繋がるため、どちらも絶対的な正義ではない。双方を役割どおりに配置するのが、レックスの秩序である。\n戦闘では光で相手の正体や能力の仕組み、隠しているものを明らかにし、闇で外部供給、逃走、再生などの繋がりを断つ。ただし、世界と複雑に絡み合った支配を完全に分離できるとは限らない。二つの神性は独立した人格や器官ではなく、一つの神格を循環しており、光にも裁定が、闇にも庇護が存在する。\n世界を管理する前に、自らの力を問い直す。\n休息と覚醒を行い、目覚めると必ず祈りを捧げる。それは他の神へ救済を求める行為ではなく、世界の根源的な秩序と自らの責任を確かめる儀式である。自分を裁定する上位者を持たないからこそ、力を振るう前にその正当性を自問する。\n『秩序』は装備でも変異でもなく神体の一部で、巨大な捕食口が物質、エネルギー、権能、管理構造を呑み込み分解する。口と牙は強力な猛毒も分泌する。普段は祭服の背面へ収められ、戦闘や権限行使の際に展開される。\n尾の肉質は柔らかくしなやかで、腰の動きに合わせて揺れ、ときには本人の意思と無関係に喜びなどの感情を表す。高い弾性と衝撃吸収性によって自他を包むエアバッグとなり、休息時には本人公認の抱き枕としても働く。\n分配\n光と闇の神性を用いて、生身で行使する能力。管理権限が届く範囲にある物質や力を捉え、衝撃、熱、神性による攻撃を、どの対象へどれだけ作用させるか割り振る。光で所在や性質、内部構造、力の流れを明らかにした物質は、移動や他の物体への侵入後も追跡でき、相手が取り込んだ空気や武装の内部を循環する力も分配先にできる。\n空気へ打ち込んだ拳の衝撃を、相手の体内にある空気へ割り当てれば、外側の装甲や結界を通過せず、内側で打撃を成立させられる。神性を帯びた衝撃が周囲の身体へ伝わるため、外装を傷つけずに内部へ致命傷を与えることもある。一撃を複数の対象へ薄く広げたり一点へ集中させたりでき、既に内部へ力を割り当てていれば、拳の軌道を避けるだけでは防ぎ切れない。\n自身や周囲が受けた攻撃も別の場所へ分け、後の反撃に利用できる。斬撃の衝撃を床や武器へ逃がし、次の接触で相手へまとめて戻すなど、受け止める動作から反撃を準備する。ただし力の総量は増えず、対象へ割り当てた力と他へ逃がした力の合計は、元の攻撃が持つ力の範囲に収まる。\n内部で攻撃を成立させても、防護や神体の性質を無条件に無視できるわけではなく、突破に足る神性と管理権限が必要となる。反管理権限による妨害には、最高位の管理主権を分配先と作用経路へ重ねて対抗する。相手が抵抗を続けていても、レックスの管理権限が優勢である間は、内部への分配を維持できる。\n闇は余分な力の広がりや不要な干渉を呑み込み、他者への巻き添えを抑える。呼吸を必要としない相手にも、内部へ取り込まれた物質や身体・武装を維持する力を捉えれば応用できるが、対象と世界を支える仕組みが複雑に絡み合い、作用させる部分を切り分けられない場合は、その対象だけを安全に処理できるとは限らない。\n致命傷を与えるだけでなく、相手の状態と戦う目的に応じて配分を調整し、戦闘能力だけを奪って命を残すこともできる。光で分配先を定め、闇で不要な広がりを取り除く働きは、一つの神格の中で同時に行われる。何を壊し、何を残すかというレックス自身の判断によって、その使い方が変わる。",
    keywords: ["六詠", "II", "仮面ライダーヴァンダール", "ヴァンダールドライバー × スペシャルコア"],
    to: "/managers/rex-loi",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "世界を残し、支配だけを終わらせるために。" },
      { no: "02", title: "他者の選択を奪わない、六詠唯一の完全なる良心。" },
      { no: "03", title: "敵の能力と逃走手段を見抜き、正面から圧倒する。" },
      { no: "04", title: "光で現実へ定着させ、闇で外の干渉を遮る。" },
      { no: "05", title: "世界を管理する前に、自らの力を問い直す。" },
      { no: "06", title: "分配" },
    ],
  },
  {
    id: "manager-shuza",
    title: "シュザ",
    category: "people",
    description: "欲望と支配を統べる主座",
    body: "欲望そのものを書き換え、従わせる。\n欲望と支配を管轄する六詠第三位。下位三名を純戦闘力、管理権限、干渉範囲の全てで凌駕する。人格、記憶、思考を残したまま『何を望むか』という根源だけを書き換え、対象に支配を自らの意思だと信じさせる。精神を奪う洗脳に頼らず、本人のまま完全に従わせる。\n生命、武器、能力、世界法則にも欲望の指向性を与え、離反や暴走を誘導する。彼女が立つ場所は万物の《主座》となり、全ての生命、概念、物語が彼女の許可なく何かを望めない完全支配領域へ変わる。世界は壊さずに残し、そこにある全ての望みを自分の所有物にしようとする。\n希望を与え、相手が自ら跪くのを待つ。\n穏やかな京都弁で語り、優雅な微笑を崩さないが、本質は悪辣で選民的である。強い信念を持つ者にはあえて希望を与え、その希望ごと自発的に差し出して隷属する瞬間を好む。上位者の実力には表面上の敬意を示すものの、忠誠を誓うことはない。\n腰まで届く白銀の髪と紅玉の瞳、深紅の花房飾りを持つ。黒、紅、紫を重ねた着物には金糸の桜と蔓草が走り、袖と裾は刃、盾、拘束帯へ変わる外装でもある。煙管状の《朱雅管》は喫煙具ではなく権限補助端末で、紅紫の霧によって周囲の欲望を可視化する。\n欲望を力に変え、紅紫の糸で攻撃の向きを操る。\n和舞の歩法から掌打と蹴りを繋ぎ、戦場に満ちる欲望を力へ変換する。紅紫の《欲糸》は肉体だけでなく攻撃、武器、能力の向きまで誘導する。管理権能を封じられても六詠第三位の基礎戦力は失われず、純粋な体術だけで戦線を制圧できる。",
    keywords: ["六詠", "III", "仮面ライダールーラー", "ディセプションガヴ × グリードゴチゾウ"],
    to: "/managers/shuza",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "欲望そのものを書き換え、従わせる。" },
      { no: "02", title: "希望を与え、相手が自ら跪くのを待つ。" },
      { no: "03", title: "欲望を力に変え、紅紫の糸で攻撃の向きを操る。" },
    ],
  },
  {
    id: "manager-opus",
    title: "オパス",
    category: "people",
    description: "祈願と代価を処理する管理人",
    body: "祈りが他者へ委ねられた瞬間、申請は受理される。\n『祈願』と『代価』を管轄する、『六詠』第五位の管理人。あらゆる世界で発生する祈り、懇願、救済要求と、それが実現することで生じる代償を管理する。\nシュザが人間の内側に存在する『欲望』を扱うのに対し、オパスはその実現を自分以外の存在へ委ねた願いを扱う。誰かに救ってほしい、神に勝たせてほしい、自分の代わりに敵を倒してほしいと、自身の選択と責任を外部へ預けた時、その願いはオパスの管理対象となる。\nオパスは願いの善悪を判断しない。世界を救いたいという祈りも、誰かを消したいという願いも、彼にとっては等しく処理すべき申請である。祈願の実現に必要な代価を算出し、要求された結果と釣り合う何かを徴収した上で、奇跡を成立させる。\nただし、オパス自身が願いを持つことはほとんどない。他者から与えられた祈願を実行することに特化しているため、能動的な判断力と戦闘意思に乏しく、通常状態における戦闘能力は六詠最下位とされる。\nしかし、明確な祈願を受理した場合、その願いを実現するために必要な出力を、代価と引き換えに際限なく獲得する。故に彼は、最弱でありながら、条件次第では上位の六詠すら滅ぼし得る存在でもある。\n願いを優先し、犠牲は顧みない。\n物静かで礼儀正しく、常に落ち着いた口調で話す。相手を脅迫することも、祈りを強要することもない。むしろ、自分へ願いを向けようとする者には一度だけ警告を行う。『私に願えば、必ず何かが失われる』と。\nそれでも願いが撤回されなかった場合、オパスは迷わず受理する。彼にとって祈願とは、願った者が代価の発生を受け入れたという意思表示である。\n願った者が具体的な代価を指定しなかった場合は、オパスの権能が願いの実現に最も適したものを自動的に選定する。それが願った本人の命であろうと、守りたかった相手であろうと、世界の未来であろうと、彼が処理を止めることはない。\nオパス自身に残虐性はなく、苦しむ姿を楽しんだり、死者を嘲笑ったりはしない。祈願を受理して代価を徴収し、結果を渡すまで、誰が破滅しても処理を止めない。悪意がなくても犠牲を顧みない、その態度が不気味さを際立たせる。\nまた、彼は自身を人間や神としてではなく、祈りを実現するための『武器』と認識している。自ら判断しないことを中立性と考え、自ら責任を負わないことを公平性と考えている。そのため、力を持つ者自身が責任を負うべきだとするレックスとは、根本的に思想が対立している。\n祈願に応じて、戦うための能力と武装を追加する。\n通常時は、六詠の中で最も消極的な戦い方をする。自ら攻勢へ出ることは少なく、重厚な装甲による防御、相手の攻撃の受け流し、内蔵兵装による迎撃を中心とする。\n技量自体は管理人相応に高いが、戦闘に勝利したいという欲望が希薄なため、攻撃には決定的な執念がない。ところが第三者から明確な祈願を受けると、戦い方は一変する。\n勝利を願われれば相手を倒す武器を、防衛なら攻撃を阻む装甲を、破壊なら対象の構造を終わらせる神兵を、徴収可能な代価の範囲内で即座に生成する。相手の攻略を目的とせず、願われた結果を成立させるために必要な能力と武装を追加し続ける。\nこのため、通常戦闘では六詠最弱でありながら、祈願成立後の必殺技出力だけは六詠でも最大級となる。祈願を受理して戦いが長引くほど、願いを叶えるための手段が追加されていく。\n祈りが個人へ向かわぬよう、顔を隠す。\n漆黒の礼装と長い外套を纏い、顔を黒いヴェールで完全に覆った大柄な男性。ヴェールの周囲には、茨と後光を組み合わせたような黄金の装飾が取り付けられている。\nオパスは、祈願を処理することが自分の役割だと考えている。祈りが『個人』に向けられることを望まないため、人間としての顔や表情を意図的に隠している。素顔を見られることへの嫌悪が理由ではない。\nヴェールの奥に本当に顔が存在するかは不明。",
    keywords: [
      "六詠",
      "V",
      "仮面ライダーモスコ",
      "戦極ドライバー × ディバインロックシード／極超ロックシード",
    ],
    to: "/managers/opus",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "祈りが他者へ委ねられた瞬間、申請は受理される。" },
      { no: "02", title: "願いを優先し、犠牲は顧みない。" },
      { no: "03", title: "祈願に応じて、戦うための能力と武装を追加する。" },
      { no: "04", title: "祈りが個人へ向かわぬよう、顔を隠す。" },
    ],
  },
  {
    id: "manager-reemu",
    title: "リームー",
    category: "people",
    description: "言い訳を現実にする男",
    body: "状況も責任も、自分に都合よく組み替える。\n六詠第六位であり、管轄そのものを必要としない管理人。侵入した世界の状況、責任、因果、運命を自分に都合のよい管理対象へ再定義し、世界全体を盤面へ変える。\nサーガ世界を含む全世界の掌握を目指し、他の六詠に先んじて独断で暗躍する。敵味方への憎愛ではなく自己保身を基準とし、他者の価値、覚悟、信念、愛情さえ自分を守るための踏み台として扱う。\n言い訳に合わせて、因果まで変える。\n表向きは温厚で争いを嫌うが、実態は排他的で責任転嫁を重ねる人物である。自己肯定感は低く承認に飢えている一方、プライドは高く敗北を認めない。自分の言い訳が成立するように因果を組み替える、『言い訳を現実にする男』である。\nオランダ貴族を思わせる姿を持ち、愛刀《天智》を帯びる。正面衝突を嫌うが、並の管理人を大きく上回る出力を持ち、生身でも戦闘できる。\n不意打ちと誘導で、戦闘前から勝利条件を変える。\n不意打ち、誘導、分断、誤認、責任転嫁、敵対関係の捏造、勝利条件の変更を重ね、戦闘が始まる前に相手が詰んだ盤面を作る。真正面から斬り結ぶ場合も《天智》による近接瞬殺へ徹し、ディルクルムサーガを圧倒する戦闘力を示す。",
    keywords: ["六詠", "VI", "仮面ライダーフリート", "デザイアドライバー × キジンソードバックル"],
    to: "/managers/reemu",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "状況も責任も、自分に都合よく組み替える。" },
      { no: "02", title: "言い訳に合わせて、因果まで変える。" },
      { no: "03", title: "不意打ちと誘導で、戦闘前から勝利条件を変える。" },
    ],
  },
  {
    id: "manager-lejas",
    title: "レジャス",
    category: "people",
    description: "世界を、勝負の盤面へ。",
    body: "『盤面』『役割』『選択肢』『勝敗条件』を管轄する六詠第四位の管理人。一位とレックスには明確な隔たりがあるが、残る四名の中では戦闘能力、管理権限、策略の全てにおいて最強であり、同時に最も悪趣味とされる。",
    keywords: [
      "六詠",
      "IV",
      "仮面ライダーファラリス",
      "ゲーマドライバー",
      "グランドマスターガシャット",
      "ゲームマスターガシャット",
    ],
    to: "/managers/lejas",
    hash: "dossier-profile",
  },
  {
    id: "rider-saga",
    title: "仮面ライダーサーガ",
    category: "riders",
    description: "滅ぼすはずだった世界を取り戻す、夢見る者。",
    body: "仲間と夢を叶え、奪われた世界を取り戻す。\n元は何の変哲もない十九歳の青年だったが、『サーガの世界』で物語の主人公シエルに選ばれてしまう。管理人から人類殲滅を強要され、仮面ライダーサーガとして世界を滅ぼす運命を背負ううち、精神は退廃していった。\n怪作の夢へ潜ったことで呪縛から解放され、新たな力を手にした。今は仲間と夢を叶え、奪われた世界を取り戻すため、味方陣営のダークホースとして戦っている。\n変身後の能力を活かした遠距離戦。\n生身の身体能力は低く、変身前の交戦を徹底して避ける。変身後は万物を拒絶する半汎用式ライダーシステムを駆使し、能力を多用した遠距離戦で本領を発揮する。\n万物を拒絶する、半汎用式​ライダーシステム。\n『拒絶』は他者から拒まれる恐怖、喪失、受け入れ難い事実、希死念慮までを含む。融合から生まれたクリスタルコアは、後の究極形態を成立させる中核となる。",
    keywords: [
      "SAGA",
      "シエル ／ 月城悠真",
      "月城 悠真",
      "月城 悠真（つきしろ ゆうま）",
      "19歳",
      "人間",
      "179cm",
      "70kg",
      "仮面ライダーサーガ",
      "エクスプリームサーガ",
      "エクスプリームサーガ",
      "エクスサーガドライバー × デュアルエクスコア",
      "エクスプリームサーガ・ウルトラ",
      "エクスプリームサーガ・ウルトラ",
      "エクスサーガドライバー × デュアルエクスコア",
      "レクソナンスサーガ",
      "レクソナンスサーガ",
      "エクスサーガドライバー × デュアルエクスコア／レクソナンスコア",
    ],
    to: "/riders/saga",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "仲間と夢を叶え、奪われた世界を取り戻す。" },
      { no: "02", title: "変身後の能力を活かした遠距離戦。" },
      { no: "03", title: "万物を拒絶する、半汎用式​ライダーシステム。" },
    ],
  },
  {
    id: "rider-realm",
    title: "仮面ライダーレルム",
    category: "riders",
    description: "REALMSが誇る完全適合者、ベル・アレイン。",
    body: "前線で戦いながら、部隊の戦況を管理する。\nベル・アレインは、検体災害と高危険度異常存在へ対抗するREALMSの元日本支部リーダー。創設者ソル・アレインと英国人の母の息子で、レルムズドライバー唯一の完全適合者である。\n自ら前線へ出ながら戦況、人員、被害予測、敵の進路を同時管理する。出生や来歴の全貌は組織内でも不明。\n軽口を絶やさず、共存できるかを見極める。\n明るく親しみやすく、冗談や軽口で場を動かす一方、意思と理性を不可逆的に失った災害は、過去の善性にかかわらず排除する。外見や出自に惑わされず、共存できるかどうかで判断する。\n生身でも、この世界で最強とされる。\n黒く染めた髪、淡い蒼の瞳、長い耳を持ち、白いコートを好む。反射神経、空間認識、情報処理に秀で、初手の必殺技と欺瞞を織り交ぜる。",
    keywords: [
      "REALM",
      "ベル・アレイン",
      "ベル・アレイン",
      "ベル・アレイン",
      "26歳",
      "男性",
      "フランス",
      "183cm",
      "76kg",
      "レルム",
      "レルムレジェンズ",
      "レルムズドライバー × レジェンズルーレット",
    ],
    to: "/riders/realm",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "前線で戦いながら、部隊の戦況を管理する。" },
      { no: "02", title: "軽口を絶やさず、共存できるかを見極める。" },
      { no: "03", title: "生身でも、この世界で最強とされる。" },
    ],
  },
  {
    id: "rider-lore",
    title: "仮面ライダーローア",
    category: "riders",
    description: "自ら弄んだ世界で、かつての敵と共闘する管理人。",
    body: "世界を弄んだ管理人は、かつての敵と並び立つ。\nサーガ世界の管理人であり、かつてシエルを殺害した経験を持つ。現在は諸事情によって弱体化し、過去に敵対した者たちとの共闘へ臨んでいる。\n憂さ晴らしに創造した世界を、バッドエンドへ導いた。\n自己肯定感は低いが、プライドは高い。口論で大敗した際の憂さ晴らしとしてサーガ世界を創造し、そこで偶然行った人助けを感謝されて舞い上がった結果、『仮面ライダーサーガ』の結末をバッドエンドへ導いた。",
    keywords: [
      "LORE",
      "ローア",
      "ローア",
      "ローア",
      "不明",
      "男性",
      "9月2日",
      "179.0cm",
      "71.2kg",
      "小林千晃",
      "ローア",
      "ローア",
      "ローアドライバー × ローアライズコア",
    ],
    to: "/riders/lore",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "世界を弄んだ管理人は、かつての敵と並び立つ。" },
      { no: "02", title: "憂さ晴らしに創造した世界を、バッドエンドへ導いた。" },
    ],
  },
  {
    id: "rider-vandal",
    title: "仮面ライダーヴァンダール",
    category: "riders",
    description: "秩序の神が振るう、破壊者の拳。",
    body: "世界を残し、支配だけを終わらせるために。\n固定された管轄を持たない六詠の管理人であり、『仮面ライダーノット』の世界を臨時で管理している。管理人達を監督する都護府のような立場から、本来なら複数の機関で分担する役割を単独で担う。率先して責任を引き受ける模範的な態度と、破壊者として猛々しく冷徹な判断を併せ持つ。\nサーガ世界の問題も自ら解決すべき事案と考えているが、その権能はローアの管理構造とともに、辛うじて維持される世界自体を破壊しかねない。誰よりも解放を望みながら自分の力だけでは実現できず、世界を残したまま管理構造だけを終わらせ得る存在を探し、他の六詠に先んじて暗躍する。\n他者の選択を奪わない、六詠唯一の完全なる良心。\n冷静沈着で慇懃かつ親切。相手の立場や能力を認めながらも自他を対等に捉え、静かな口調と寛容さを崩さない。善意や友情、使命感を軽んじるように振る舞うことはあっても、その力を正確に理解して尊重し、意図的に踏みにじることはない。\n戦闘を『儀式』と呼び、他者の選択を奪ってきた絶対者に、自らの誤りと敗北を理解させるために破壊を行う。その際にも人格や尊厳を弄ぶことはない。策略に長け、必要なら正面戦闘や敵対者との一時的な共闘も選び、第一位と同等の行動権を用いて事案の解決へ協力する。\n予測を外す存在は重要な観測対象とするが、脅威か救済の可能性かを見極めるまでは排除しない。提案の拒絶も当然の自衛として尊重し、不利益を与えることはなく、過去に協力を断った者からの救援にも真摯に応じる。\n敵の能力と逃走手段を見抜き、正面から圧倒する。\n卓越した身体能力による近接格闘を軸に、敵の能力、思考、関係性、戦闘履歴を解析する。逃走経路や反撃手段、能力の発動条件、精神的な支柱まで把握してなお正面から圧倒することを、支配の根拠を最も効率よく破壊する手段と考えている。戦闘開始直後には、あえて防御や回避を抑えて攻撃を観察する。\n光で現実へ定着させ、闇で外の干渉を遮る。\nブロンドの髪と人ならざる麗貌、豪奢な祭服を持つ青年の姿を取るが、人間ではない。人々の想いが集積して成立した『秩序の神』であり、通常の物理攻撃は通用せず、口内には鋭い毒牙を備える。神体の人型部分には光、蛇状の尾『秩序』には闇の神性が強く表れる。\n光は隠されたものを明らかにし、生命、意思、法則を現実へ定着させる力。闇は外部の干渉を遮って休息を与え、過剰な力や不要な構造を呑み込み、静寂へ還す力である。過剰な光は監視と支配に、過剰な闇は停滞と消失に繋がるため、どちらも絶対的な正義ではない。双方を役割どおりに配置するのが、レックスの秩序である。\n戦闘では光で相手の正体や能力の仕組み、隠しているものを明らかにし、闇で外部供給、逃走、再生などの繋がりを断つ。ただし、世界と複雑に絡み合った支配を完全に分離できるとは限らない。二つの神性は独立した人格や器官ではなく、一つの神格を循環しており、光にも裁定が、闇にも庇護が存在する。\n世界を管理する前に、自らの力を問い直す。\n休息と覚醒を行い、目覚めると必ず祈りを捧げる。それは他の神へ救済を求める行為ではなく、世界の根源的な秩序と自らの責任を確かめる儀式である。自分を裁定する上位者を持たないからこそ、力を振るう前にその正当性を自問する。\n『秩序』は装備でも変異でもなく神体の一部で、巨大な捕食口が物質、エネルギー、権能、管理構造を呑み込み分解する。口と牙は強力な猛毒も分泌する。普段は祭服の背面へ収められ、戦闘や権限行使の際に展開される。\n尾の肉質は柔らかくしなやかで、腰の動きに合わせて揺れ、ときには本人の意思と無関係に喜びなどの感情を表す。高い弾性と衝撃吸収性によって自他を包むエアバッグとなり、休息時には本人公認の抱き枕としても働く。\n分配\n光と闇の神性を用いて、生身で行使する能力。管理権限が届く範囲にある物質や力を捉え、衝撃、熱、神性による攻撃を、どの対象へどれだけ作用させるか割り振る。光で所在や性質、内部構造、力の流れを明らかにした物質は、移動や他の物体への侵入後も追跡でき、相手が取り込んだ空気や武装の内部を循環する力も分配先にできる。\n空気へ打ち込んだ拳の衝撃を、相手の体内にある空気へ割り当てれば、外側の装甲や結界を通過せず、内側で打撃を成立させられる。神性を帯びた衝撃が周囲の身体へ伝わるため、外装を傷つけずに内部へ致命傷を与えることもある。一撃を複数の対象へ薄く広げたり一点へ集中させたりでき、既に内部へ力を割り当てていれば、拳の軌道を避けるだけでは防ぎ切れない。\n自身や周囲が受けた攻撃も別の場所へ分け、後の反撃に利用できる。斬撃の衝撃を床や武器へ逃がし、次の接触で相手へまとめて戻すなど、受け止める動作から反撃を準備する。ただし力の総量は増えず、対象へ割り当てた力と他へ逃がした力の合計は、元の攻撃が持つ力の範囲に収まる。\n内部で攻撃を成立させても、防護や神体の性質を無条件に無視できるわけではなく、突破に足る神性と管理権限が必要となる。反管理権限による妨害には、最高位の管理主権を分配先と作用経路へ重ねて対抗する。相手が抵抗を続けていても、レックスの管理権限が優勢である間は、内部への分配を維持できる。\n闇は余分な力の広がりや不要な干渉を呑み込み、他者への巻き添えを抑える。呼吸を必要としない相手にも、内部へ取り込まれた物質や身体・武装を維持する力を捉えれば応用できるが、対象と世界を支える仕組みが複雑に絡み合い、作用させる部分を切り分けられない場合は、その対象だけを安全に処理できるとは限らない。\n致命傷を与えるだけでなく、相手の状態と戦う目的に応じて配分を調整し、戦闘能力だけを奪って命を残すこともできる。光で分配先を定め、闇で不要な広がりを取り除く働きは、一つの神格の中で同時に行われる。何を壊し、何を残すかというレックス自身の判断によって、その使い方が変わる。",
    keywords: [
      "VANDAL",
      "レックス・ロワ",
      "レックス・ロワ",
      "レックス・ロワ",
      "六詠・第二位",
      "不明",
      "両性具有（性自認は女性。本人に強い自覚はない）",
      "185.0cm",
      "80.1kg",
      "秩序の神",
      "秩序／破壊・固定管轄なし",
      "仮面ライダーヴァンダール",
      "ACCESS GRANTED",
      "ヴァンダール",
      "ヴァンダール",
      "ヴァンダールドライバー × スペシャルコア",
    ],
    to: "/riders/vandal",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "世界を残し、支配だけを終わらせるために。" },
      { no: "02", title: "他者の選択を奪わない、六詠唯一の完全なる良心。" },
      { no: "03", title: "敵の能力と逃走手段を見抜き、正面から圧倒する。" },
      { no: "04", title: "光で現実へ定着させ、闇で外の干渉を遮る。" },
      { no: "05", title: "世界を管理する前に、自らの力を問い直す。" },
      { no: "06", title: "分配" },
    ],
  },
  {
    id: "rider-leddic",
    title: "仮面ライダーレディック",
    category: "riders",
    description: "規格外の幸運で、核心へ辿り着く警部補。",
    body: "何気ない一言で、事件の核心を突く。\n現場叩き上げで捜査一課へ進んだ警部補。無口で冷静に見えるが、実際は口下手で深く考えていないことが多い。何気なく口にした言葉が事件の核心を突き、遭遇した人物がたまたま犯人だったという規格外の強運を持つ。\n負け知らずの体術と、設計通りに使わない能力。\n柔道、空手、剣道、捕縛術で性別を問わず一度も敗れたことがない。腕時計型の変身装置『レディックウォッチ』を用い、与えられた能力を設計通りに扱わず、悪知恵と幸運で転用する。",
    keywords: [
      "LEDDIC",
      "在原華火",
      "在原華火",
      "在原華火（ありはら はなか）",
      "24歳",
      "女性",
      "176cm",
      "71kg",
      "捜査一課・警部補",
      "レディック",
      "レディック",
      "四八式腕時計型偏装甲装置 × レディックウォッチ",
      "レディック",
      "レディック",
      "四八式腕時計型偏装甲装置 × レディックウォッチ",
      "無神 千桐",
      "レディック",
      "レディック",
    ],
    to: "/riders/leddic",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "何気ない一言で、事件の核心を突く。" },
      { no: "02", title: "負け知らずの体術と、設計通りに使わない能力。" },
    ],
  },
  {
    id: "rider-argenome",
    title: "仮面ライダーアルゲノム",
    category: "riders",
    description: "病を頂戴する、高速の義賊。",
    body: "幻想郷を救った、紅魔館の執事。\n紅魔館の執事として仕え、幻想郷を救った紅城真守。ゲーマドライバーへライダーガシャットを装填することで、仮面ライダーアルゲノムへ変身する。\n高速機動と無音の接近。\nファントムローブは布が風に揺れる音まで消し、ブーツも足音を発生させない。敵を探して音を立てずに接近し、攻撃とともに駆除プログラムを流し込む。",
    keywords: [
      "ARGENOME",
      "紅城真守",
      "紅城真守",
      "紅城真守",
      "不明",
      "男性",
      "紅魔館の執事",
      "ゲーマドライバー",
      "ガシャコンエッジ",
      "アルゲノム",
      "アルゲノム",
      "ゲーマドライバー × ライダーガシャット",
    ],
    to: "/riders/argenome",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "幻想郷を救った、紅魔館の執事。" },
      { no: "02", title: "高速機動と無音の接近。" },
    ],
  },
  {
    id: "rider-over-zeztz",
    title: "仮面ライダーオーバーゼッツ",
    category: "riders",
    description: "英国支部から派遣された、最強のエージェント。",
    body: "軽口を飛ばしながら、任務を遂行する。\nコードナンバー・セヴンを名乗るCODE英国支部のエージェント。陽気な軽口を飛ばしながらも任務に最適な手段を選び、改良型ゼッツシステムを駆る。近接戦闘と銃器の扱いから潜入、解析、情報回収まで、一人でこなす。\n戦闘・潜入・解析を支えるCODE装備。\nゼッツフォン、ゼッツカメラ、ゼッツセンサー、ゼッツライセンスを任務に用いる。エージェントとしての身分と装備を伴い、世界の境界を越えて活動する。",
    keywords: [
      "OVER ZEZTZ",
      "ジェームズ・スミス",
      "ジェームズ・スミス",
      "James Smith",
      "セヴン",
      "28歳",
      "男性",
      "185cm",
      "CODE英国支部",
      "エージェント",
      "オーバーゼッツ",
      "オーバーゼッツ",
      "ゼッツドライバー × フィジカムインパクトカプセム",
    ],
    to: "/riders/over-zeztz",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "軽口を飛ばしながら、任務を遂行する。" },
      { no: "02", title: "戦闘・潜入・解析を支えるCODE装備。" },
    ],
  },
  {
    id: "rider-cipher",
    title: "仮面ライダーサイファー",
    category: "riders",
    description: "SCARS特務情報官",
    body: "スカーズに所属する、謎の男。\n正体不明の組織『スカーズ』で特務情報官を務める、謎の男。\n相手にどう見られているかを、正確に把握する。\n徹底したプロフェッショナル。目的、必要情報、成功条件、撤退条件を常に切り分け、感情的な好悪を任務判断へ混ぜることを嫌う。愛想を振り撒かず、信用を獲得すること自体にも興味を示さない。潜入で重要なのは好かれることではなく、《相手が自分をどういう人物だと思っているかを把握し、その認識から逸脱しないこと》だと考えているからだ。\nそのため必要とあれば敵を助け、味方を攻撃し、故意に任務を失敗し、時には本当に仲間へ損害を与える判断すら行う。\n準備不足の犠牲を、必要な犠牲と呼ばない。\n無関係な人間を使い捨てることを極端に嫌う。任務上どうしても避けられなかった犠牲と、自分たちの無能や準備不足が生んだ犠牲を同じ言葉で処理する者へは、露骨な嫌悪を向ける。「必要な犠牲だった、で報告書を閉じる奴は大体ただの馬鹿だ」という言葉には、損失を数字へ変換して責任から逃げる態度への拒絶が表れている。\nベルとは情報を共有し、悠真には敵意を演じる。\n口調は冷静だが、育ちの良いフランス人らしい言葉遣いからは少し遠く、親しい相手ほど口が悪くなる。特にベルとは旧知のため容赦がない。ベル側も彼の態度には慣れており、互いに悪態を吐きながら必要な情報だけは正確に交換する。\n悠真に対しては潜入任務の都合上、長期間明確な敵意を演じる。それは演技ではあるが、彼自身も悠真の危うい自己犠牲性には苛立ちを覚えており、本気で批判する。皮肉なことに、後に彼自身が悠真を庇って死亡する。\n偽装と経路追跡で、敵の判断を狂わせる。\nサイファーシステムは潜入、偽装、情報収集、対組織工作を主目的として開発された。認証信号の偽装、能力や命令の経路追跡、位置情報などへの偽信号の混入によって、《情報的不確定性》を利用して戦う。\n潜入継続が不可能となった場合、あるいは対象の確実な排除が必要な場合にはブラックサイトへ移行。偽装へ割り当てていた演算資源とEMPの大部分を身体駆動、武装、敵解析へ転用する。",
    keywords: [
      "CIPHER",
      "リュシアン・ヴァレール",
      "リュシアン・ヴァレール",
      "リュシアン・ヴァレール",
      "30歳",
      "男性",
      "フランス",
      "186.2cm",
      "78.4kg",
      "SCARS",
      "特務情報官",
      "内山昂輝",
      "サイファー",
      "サイファー",
      "サイファードライバー × プロキシコア",
      "サイファー・ブラックサイト",
      "サイファー・ブラックサイト",
      "サイファードライバー × プライムコア",
    ],
    to: "/riders/cipher",
    hash: "dossier-profile",
    sections: [
      { no: "01", title: "スカーズに所属する、謎の男。" },
      { no: "02", title: "相手にどう見られているかを、正確に把握する。" },
      { no: "03", title: "準備不足の犠牲を、必要な犠牲と呼ばない。" },
      { no: "04", title: "ベルとは情報を共有し、悠真には敵意を演じる。" },
      { no: "05", title: "偽装と経路追跡で、敵の判断を狂わせる。" },
    ],
  },
  {
    id: "system-extreme-01",
    title: "受けた攻撃が、対抗策に。",
    category: "systems",
    description:
      "受けた攻撃と戦況を学習し、相手が同じ手で優位に立てないよう対抗手段を更新します。戦闘が続くほど、勝利へ至る経路が増えていきます。",
    keywords: ["LEARNING", "エクスプリームサーガ"],
    to: "/extreme-saga",
    hash: "system",
  },
  {
    id: "system-extreme-02",
    title: "暗黒物質を、戦う出力へ。",
    category: "systems",
    description:
      "戦況に応じて暗黒物質系の出力を充填し、増殖した戦闘経路を実行するためのエネルギーを供給します。生み出した選択肢を、実際の攻撃へ繋げます。",
    keywords: ["DARK MATTER CHARGING", "エクスプリームサーガ"],
    to: "/extreme-saga",
    hash: "system",
  },
  {
    id: "system-extreme-03",
    title: "決着を固定する。",
    category: "systems",
    description:
      "複数の可能性から決着へ至る結果を選び、攻撃・防御・修復を同じ結論へ収束させます。ウルトラでは50秒間、その固定を限界まで強化します。",
    keywords: ["HIGH SUPREME", "エクスプリームサーガ"],
    to: "/extreme-saga",
    hash: "system",
  },
  {
    id: "system-rexonance-01",
    title: "超自己進化",
    category: "systems",
    description:
      "観測した敵能力と戦況をもとに、次世代の装甲・演算・権限構造を生み出します。戦闘中も攻撃の周波数、位相、権限署名を更新し続けます。",
    keywords: ["EVOLUTION", "レクソナンスサーガ"],
    to: "/rexonance-saga",
    hash: "system",
  },
  {
    id: "system-rexonance-02",
    title: "絶対秩序",
    category: "systems",
    description:
      "進化した要素へ境界と役割を与え、互いに矛盾なく働くよう即座に固定します。進化を続けながらも、自己崩壊を防ぎます。",
    keywords: ["ABSOLUTE ORDER", "レクソナンスサーガ"],
    to: "/rexonance-saga",
    hash: "system",
  },
  {
    id: "system-rexonance-03",
    title: "月城悠真の意思",
    category: "systems",
    description:
      "レックスとゼウスはそれぞれの存在を保ったまま悠真と超共鳴し、何を破壊し、何を残すかは、最後まで悠真自身が決めます。",
    keywords: ["HUMAN WILL", "レクソナンスサーガ"],
    to: "/rexonance-saga",
    hash: "system",
  },
];

/** Every string of published prose inside a record (no paths, colours or codes). */
function proseOf(value: unknown, out: string[] = []): string[] {
  if (typeof value === "string") {
    if (/[\u3040-\u30ff\u4e00-\u9fff]/.test(value) && !value.startsWith("/")) out.push(value);
  } else if (Array.isArray(value)) {
    for (const item of value) proseOf(item, out);
  } else if (value && typeof value === "object") {
    for (const [key, item] of Object.entries(value)) {
      if (!["image", "alt", "accent", "src", "pos", "assets", "img"].includes(key))
        proseOf(item, out);
    }
  }
  return out;
}

const SAGA_RECORD = DOSSIER_DOCUMENTS.find((document) => document.id === "rider-saga")!;

const SPECIAL_SITE_DOCUMENTS = (Object.keys(SPECIAL_SITE_SECTIONS) as SpecialSiteId[]).flatMap(
  (site) =>
    SPECIAL_SITE_SECTIONS[site]
      .filter(([hash]) => hash !== "top")
      .map(([hash, label, code]): SearchCatalogueDocument => ({
        id: `site-${site}-${hash}`,
        title: `${SPECIAL_SITE_TITLES[site]}／${label}`,
        category: "pages",
        description: `${SPECIAL_SITE_TITLES[site]}の「${label}」へ。`,
        keywords: [label, code, SPECIAL_SITE_TITLES[site]],
        to: SPECIAL_SITE_PATHS[site],
        hash,
      })),
);

const LIBRARY_PAGE_ANCHORS: Record<string, string> = {
  world: "top",
  dream: "top",
  gallery: "gallery-collection",
};

/** The library's English and romaji spellings for the same destination. */
const aliasesFor = (to: string): string[] =>
  LIBRARY_ENTRIES.filter((entry) => entry.path === to && !entry.hash).flatMap(
    (entry) => entry.aliases,
  );

const withAliases = (document: SearchCatalogueDocument): SearchCatalogueDocument => {
  const aliases = aliasesFor(document.to);
  return aliases.length && document.hash === "dossier-profile"
    ? { ...document, aliases: [...(document.aliases ?? []), ...aliases] }
    : document;
};

export const SEARCH_DOCUMENTS: readonly SearchCatalogueDocument[] = [
  ...DOSSIER_DOCUMENTS,
  {
    id: "person-dante",
    title: "ダンテ",
    category: "people",
    description: DANTE_SECTIONS[0].title,
    body: DANTE_SECTIONS.flatMap((section) => [section.title, ...section.body]).join("\n"),
    sections: DANTE_SECTIONS.map(({ no, title }) => ({ no, title })),
    keywords: [
      ...DANTE_FACTS.map((row) => row.dd),
      ...DANTE_FORMS.flatMap((form) => [form.name, form.system]),
    ],
    to: "/characters/dante",
    hash: "dossier-profile",
  },
  {
    id: "person-ciel",
    title: "シエル",
    category: "people",
    description: SAGA_RECORD.description,
    body: SAGA_RECORD.body,
    sections: SAGA_RECORD.sections,
    keywords: ["RE DIVE", "六詠", "RIKUEI I", "月城悠真", "仮面ライダーサーガ"],
    to: "/characters/ciel",
    hash: "dossier-profile",
  },
  ...(["terra", "luna"] as const).map((id): SearchCatalogueDocument => {
    const roster = WORLD_CAST_ROSTER.find((person) => person.id === id)!;
    const sections = RELATED_SECTIONS[id];
    return {
      id: `character-${id}`,
      title: roster.name,
      category: "people",
      description: sections[0].title,
      body: sections.flatMap((section) => [section.title, ...section.body]).join("\n"),
      sections: sections.map(({ no, title }) => ({ no, title })),
      keywords: [roster.role, ...sections.map((section) => section.kicker)],
      to: `/characters/${id}`,
      hash: "dossier-profile",
    };
  }),
  {
    id: "character-yoake-mamori",
    title: "夜明護尊",
    category: "people",
    description: YOAKE_MAMORI_SECTIONS[0].title,
    body: YOAKE_MAMORI_SECTIONS.flatMap((section) => [section.title, ...section.body]).join("\n"),
    sections: YOAKE_MAMORI_SECTIONS.map(({ no, title }) => ({ no, title })),
    keywords: ["よあけまもりのみこと", ...YOAKE_MAMORI_SECTIONS.map((section) => section.kicker)],
    to: "/characters/yoake-mamori",
    hash: "dossier-profile",
  },
  ...WORLD_CAST_ROSTER.map((person): SearchCatalogueDocument => ({
    id: "person-" + person.id,
    title: person.name,
    category: "people",
    description: person.role,
    body: person.profile.map((part) => part.text).join("\n"),
    keywords: [person.role, ...(person.line ? [person.line] : [])],
    to: person.to ?? "/world",
    hash: person.to ? "dossier-profile" : "wa-person-" + person.id,
    secondary: Boolean(person.to),
  })),
  ...DREAM_CAST_ROSTER.map((person): SearchCatalogueDocument => ({
    id: "dream-person-" + person.id,
    title: person.name,
    category: "people",
    description: person.profile[0],
    body: person.profile.join("\n"),
    keywords: ["DREAM CHAPTER", "ドリームチャプター", person.affiliation, person.line],
    to: "/dream-chapter",
    hash: "dream-roster-" + person.id,
  })),
  ...DREAM_CHARACTERS.map((person): SearchCatalogueDocument => ({
    id: "dream-dossier-" + person.id,
    title: person.name,
    category: "people",
    description: person.role,
    body: person.sections
      .flatMap((section) => [
        section.title,
        ...(section.lead ? [section.lead] : []),
        ...(section.paragraphs ?? []),
        ...(section.items ?? []).map((item) => item.name + " " + item.body),
      ])
      .join("\n"),
    keywords: [
      "DREAM CHAPTER",
      "ドリームチャプター",
      person.roman,
      person.role,
      ...person.profile.map((row) => row.value),
    ],
    to: "/dream-chapter",
    hash: "dream-character-" + person.id,
  })),
  ...DREAM_DOLMINENCE.map((record): SearchCatalogueDocument => ({
    id: "dream-dolminence-" + record.id,
    title: record.name,
    category: "people",
    description: record.paragraphs[0],
    body: [...record.paragraphs, ...record.items.map((item) => item.name + " " + item.body)].join(
      "\n",
    ),
    keywords: ["ドルミネンス", record.roman],
    to: "/dream-chapter",
    hash: "dream-dolminence-" + record.id,
  })),
  ...CAST.map((person): SearchCatalogueDocument => ({
    id: "final-stage-cast-" + person.id,
    title: person.name,
    category: "people",
    description: person.role,
    body: person.body.join("\n"),
    keywords: ["FINAL STAGE", "ファイナルステージ", person.en, person.kicker],
    to: "/final-stage",
    hash: "characters",
  })),
  ...DREAM_CASES.map((episode): SearchCatalogueDocument => ({
    id: "dream-case-" + episode.no,
    title: "CASE " + episode.no + "「" + episode.title + "」",
    category: "story",
    description: episode.lead,
    body: episode.paragraphs.join("\n"),
    keywords: ["DREAM CHAPTER", "ドリームチャプター", episode.reading],
    to: "/dream-chapter",
    hash: "dream-case-" + episode.no,
  })),
  ...WORLD_EPISODE_NOTES.map((episode): SearchCatalogueDocument => ({
    id: "world-episode-" + episode.no,
    title: "EPISODE " + episode.no + " " + episode.title,
    category: "story",
    description: episode.synopsis[0],
    body: episode.synopsis.join("\n"),
    keywords: ["Deception World", "ディセプションワールド", episode.stage],
    to: "/world",
    hash: "wa-episode-" + episode.no,
  })),
  {
    id: "final-stage",
    title: "仮面ライダーサーガ FINAL STAGE",
    category: "story",
    description:
      "仮面ライダーファーフロムサーガと仮面ライダーレルムロイヤル、ファイナルステージ限定の二形態の記録を収録。",
    body: [STORY.title, STORY.lead, ...STORY.paragraphs].join("\n"),
    keywords: ["ファイナルステージ", "ファーフロムサーガ", "レルムロイヤル"],
    to: "/final-stage",
    hash: "story",
  },
  ...WORLD_COLUMNS.map((column): SearchCatalogueDocument => ({
    id: "world-column-" + column.no,
    title: "コラム" + column.no + " " + column.title,
    category: "world",
    description: column.body,
    body: column.pickup.join("\n"),
    keywords: ["世界観コラム", "WORLD COLUMN", column.kicker],
    to: "/world",
    hash: "world-column-" + column.no,
  })),
  ...WORLD_BRIEF.map((entry): SearchCatalogueDocument => ({
    id: "world-brief-" + entry.id,
    title: entry.name,
    category: "world",
    description: entry.body[0],
    body: entry.body.join("\n"),
    keywords: [entry.code],
    to: "/world",
    hash: "wa-brief-" + entry.id,
  })),
  ...WORLD_GLOSSARY.map((entry): SearchCatalogueDocument => ({
    id: "world-term-" + entry.term,
    title: entry.term,
    category: "world",
    description: entry.body[0],
    body: entry.body.join("\n"),
    to: "/world",
    hash: "wa-term-" + entry.term,
  })),
  ...WORLD_LOCATIONS.map((entry): SearchCatalogueDocument => ({
    id: "world-location-" + entry.name,
    title: entry.name,
    category: "world",
    description: entry.text,
    to: "/world",
    hash: "wa-location-" + entry.name,
  })),
  ...DREAM_FACTIONS.map((faction): SearchCatalogueDocument => ({
    id: "dream-faction-" + faction.id,
    title: faction.name,
    category: "world",
    description: faction.statements[0]?.text ?? faction.name,
    body: proseOf([
      faction.statements.map((statement) => statement.text),
      faction.members?.map((member) => member.name + " " + member.note),
      faction.pact,
      faction.creed,
      faction.limit,
    ]).join("\n"),
    keywords: [
      "DREAM CHAPTER",
      "ドリームチャプター",
      ...(faction.members ?? []).map((member) => member.name),
    ],
    to: "/dream-chapter",
    hash: "dream-faction-" + faction.id,
  })),
  ...DREAM_GLOSSARY.map((entry): SearchCatalogueDocument => ({
    id: "dream-term-" + entry.term,
    title: entry.term,
    category: "world",
    description: entry.body[0] ?? entry.said ?? entry.term,
    body: [...entry.body, ...(entry.said ? [entry.said] : [])].join("\n"),
    keywords: ["DREAM CHAPTER", "ドリームチャプター", "用語集"],
    to: "/dream-chapter",
    hash: "glossary",
  })),
  {
    id: "extreme-saga",
    title: "仮面ライダーエクスプリームサーガ",
    category: "riders",
    description: "殴り合い、歓迎。長引くほど、こっちのもの。",
    keywords: ["エクスプリームサーガ・ウルトラ", "EXTREME", "P14", "性能比較"],
    aliases: ["extreme saga"],
    to: "/extreme-saga",
    hash: "top",
  },
  {
    id: "rexonance-saga",
    title: "仮面ライダーレクソナンスサーガ",
    category: "riders",
    description:
      "究極が始まる。レクソナンスサーガの標準性能を、公開済みのカタログ値で。P14演算基盤、三つの形態、三者の共鳴構造まで。",
    keywords: ["HIGH", "MAX", "ULTRA", "SA-GA OS 5.5", "P14", "TRINITY RESONANCE"],
    aliases: ["rexonance saga"],
    to: "/rexonance-saga",
    hash: "top",
  },
  {
    id: "far-from-saga",
    title: "仮面ライダーファーフロムサーガ",
    category: "riders",
    description: "SA-GA OS 6.0",
    body: proseOf([FAR_FROM_SAGA.overview, FAR_FROM_SAGA.theories, FAR_FROM_SAGA.stages]).join(
      "\n",
    ),
    keywords: [
      "FINAL STAGE",
      "FARFROM DRIVE",
      "ファーフロムビット",
      FAR_FROM_SAGA.en,
      ...Object.values(FAR_FROM_SAGA.stages).map((stage) => stage.label),
    ],
    to: "/final-stage",
    hash: "far-from-saga",
  },
  {
    id: "realm-royal",
    title: "仮面ライダーレルムロイヤル",
    category: "riders",
    description: "ロイヤル・マルチタイプ",
    body: proseOf([REALM_ROYAL.overview, REALM_ROYAL.armor, REALM_ROYAL.abilities]).join("\n"),
    keywords: [
      "FINAL STAGE",
      "ROYALLL",
      "パラレム・ロイヤル",
      REALM_ROYAL.en,
      ...Object.values(REALM_ROYAL.forms).map((form) => form.name),
    ],
    to: "/final-stage",
    hash: "realm-royal",
  },
  {
    id: "form-archive",
    title: "フォームアーカイブ",
    category: "forms",
    description: "仮面ライダーサーガと仮面ライダーレルムのフォーム一覧・スペック・比較アーカイブ。",
    keywords: ["サーガ", "レルム", "性能比較", "フォーム検索", "レルムレジェンズ"],
    aliases: ["form archive"],
    to: "/form-archive",
    hash: "archive-switcher",
  },
  ...FORM_ARCHIVE_FORMS.map((form): SearchCatalogueDocument => ({
    id: `form-${form.archive}-${form.id}`,
    title: form.name,
    category: "forms",
    description:
      form.tier || (form.archive === "realm" ? "仮面ライダーレルム" : "仮面ライダーサーガ"),
    keywords: [
      form.archive === "realm" ? "仮面ライダーレルム" : "仮面ライダーサーガ",
      form.archive === "realm" ? "REALM" : "SAGA",
      "フォームアーカイブ",
    ],
    to: "/form-archive",
    hash: "archive-switcher",
    // The archive opens on the form itself (?form=, rx6 shareable state).
    search: form.archive === "realm" ? { archive: "realm", form: form.id } : { form: form.id },
  })),
  ...LIBRARY_ENTRIES.filter((entry) => entry.id in LIBRARY_PAGE_ANCHORS).map(
    (entry): SearchCatalogueDocument => ({
      id: "page-" + entry.id,
      title: entry.title,
      category: "pages",
      description: entry.description,
      aliases: entry.aliases,
      to: entry.path,
      hash: entry.hash ?? LIBRARY_PAGE_ANCHORS[entry.id],
    }),
  ),
  ...SPECIAL_SITE_DOCUMENTS,
].map(withAliases);
