/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagersRouteImport } from './routes/managers'
import { Route as RidersRouteImport } from './routes/riders'
import { Route as WorldRouteImport } from './routes/world'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as CharactersLunaRouteImport } from './routes/characters/luna'
import { Route as CharactersTerraRouteImport } from './routes/characters/terra'
import { Route as ManagersLejasRouteImport } from './routes/managers/lejas'
import { Route as ManagersReemuRouteImport } from './routes/managers/reemu'
import { Route as ManagersRexLoiRouteImport } from './routes/managers/rex-loi'
import { Route as ManagersShuzaRouteImport } from './routes/managers/shuza'
import { Route as RidersIdRouteImport } from './routes/riders/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersRoute = ManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => rootRouteImport,
} as any)
const RidersRoute = RidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersLunaRoute = CharactersLunaRouteImport.update({
  id: '/luna',
  path: '/luna',
  getParentRoute: () => CharactersRoute,
} as any)
const CharactersTerraRoute = CharactersTerraRouteImport.update({
  id: '/terra',
  path: '/terra',
  getParentRoute: () => CharactersRoute,
} as any)
const ManagersLejasRoute = ManagersLejasRouteImport.update({
  id: '/lejas',
  path: '/lejas',
  getParentRoute: () => ManagersRoute,
} as any)
const ManagersReemuRoute = ManagersReemuRouteImport.update({
  id: '/reemu',
  path: '/reemu',
  getParentRoute: () => ManagersRoute,
} as any)
const ManagersRexLoiRoute = ManagersRexLoiRouteImport.update({
  id: '/rex-loi',
  path: '/rex-loi',
  getParentRoute: () => ManagersRoute,
} as any)
const ManagersShuzaRoute = ManagersShuzaRouteImport.update({
  id: '/shuza',
  path: '/shuza',
  getParentRoute: () => ManagersRoute,
} as any)
const RidersIdRoute = RidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RidersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/managers': typeof ManagersRouteWithChildren
  '/riders': typeof RidersRouteWithChildren
  '/world': typeof WorldRoute
  '/api/export': typeof ApiExportRoute
  '/characters/luna': typeof CharactersLunaRoute
  '/characters/terra': typeof CharactersTerraRoute
  '/managers/lejas': typeof ManagersLejasRoute
  '/managers/reemu': typeof ManagersReemuRoute
  '/managers/rex-loi': typeof ManagersRexLoiRoute
  '/managers/shuza': typeof ManagersShuzaRoute
  '/riders/$id': typeof RidersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/managers': typeof ManagersRouteWithChildren
  '/riders': typeof RidersRouteWithChildren
  '/world': typeof WorldRoute
  '/api/export': typeof ApiExportRoute
  '/characters/luna': typeof CharactersLunaRoute
  '/characters/terra': typeof CharactersTerraRoute
  '/managers/lejas': typeof ManagersLejasRoute
  '/managers/reemu': typeof ManagersReemuRoute
  '/managers/rex-loi': typeof ManagersRexLoiRoute
  '/managers/shuza': typeof ManagersShuzaRoute
  '/riders/$id': typeof RidersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/managers': typeof ManagersRouteWithChildren
  '/riders': typeof RidersRouteWithChildren
  '/world': typeof WorldRoute
  '/api/export': typeof ApiExportRoute
  '/characters/luna': typeof CharactersLunaRoute
  '/characters/terra': typeof CharactersTerraRoute
  '/managers/lejas': typeof ManagersLejasRoute
  '/managers/reemu': typeof ManagersReemuRoute
  '/managers/rex-loi': typeof ManagersRexLoiRoute
  '/managers/shuza': typeof ManagersShuzaRoute
  '/riders/$id': typeof RidersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/download'
    | '/login'
    | '/managers'
    | '/riders'
    | '/world'
    | '/api/export'
    | '/characters/luna'
    | '/characters/terra'
    | '/managers/lejas'
    | '/managers/reemu'
    | '/managers/rex-loi'
    | '/managers/shuza'
    | '/riders/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/download'
    | '/login'
    | '/managers'
    | '/riders'
    | '/world'
    | '/api/export'
    | '/characters/luna'
    | '/characters/terra'
    | '/managers/lejas'
    | '/managers/reemu'
    | '/managers/rex-loi'
    | '/managers/shuza'
    | '/riders/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/download'
    | '/login'
    | '/managers'
    | '/riders'
    | '/world'
    | '/api/export'
    | '/characters/luna'
    | '/characters/terra'
    | '/managers/lejas'
    | '/managers/reemu'
    | '/managers/rex-loi'
    | '/managers/shuza'
    | '/riders/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  ManagersRoute: typeof ManagersRouteWithChildren
  RidersRoute: typeof RidersRouteWithChildren
  WorldRoute: typeof WorldRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers': {
      id: '/managers'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof ManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riders': {
      id: '/riders'
      path: '/riders'
      fullPath: '/riders'
      preLoaderRoute: typeof RidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/luna': {
      id: '/characters/luna'
      path: '/luna'
      fullPath: '/characters/luna'
      preLoaderRoute: typeof CharactersLunaRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/characters/terra': {
      id: '/characters/terra'
      path: '/terra'
      fullPath: '/characters/terra'
      preLoaderRoute: typeof CharactersTerraRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/managers/lejas': {
      id: '/managers/lejas'
      path: '/lejas'
      fullPath: '/managers/lejas'
      preLoaderRoute: typeof ManagersLejasRouteImport
      parentRoute: typeof ManagersRoute
    }
    '/managers/reemu': {
      id: '/managers/reemu'
      path: '/reemu'
      fullPath: '/managers/reemu'
      preLoaderRoute: typeof ManagersReemuRouteImport
      parentRoute: typeof ManagersRoute
    }
    '/managers/rex-loi': {
      id: '/managers/rex-loi'
      path: '/rex-loi'
      fullPath: '/managers/rex-loi'
      preLoaderRoute: typeof ManagersRexLoiRouteImport
      parentRoute: typeof ManagersRoute
    }
    '/managers/shuza': {
      id: '/managers/shuza'
      path: '/shuza'
      fullPath: '/managers/shuza'
      preLoaderRoute: typeof ManagersShuzaRouteImport
      parentRoute: typeof ManagersRoute
    }
    '/riders/$id': {
      id: '/riders/$id'
      path: '/$id'
      fullPath: '/riders/$id'
      preLoaderRoute: typeof RidersIdRouteImport
      parentRoute: typeof RidersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CharactersRouteChildren {
  CharactersLunaRoute: typeof CharactersLunaRoute
  CharactersTerraRoute: typeof CharactersTerraRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersLunaRoute: CharactersLunaRoute,
  CharactersTerraRoute: CharactersTerraRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

interface ManagersRouteChildren {
  ManagersLejasRoute: typeof ManagersLejasRoute
  ManagersReemuRoute: typeof ManagersReemuRoute
  ManagersRexLoiRoute: typeof ManagersRexLoiRoute
  ManagersShuzaRoute: typeof ManagersShuzaRoute
}

const ManagersRouteChildren: ManagersRouteChildren = {
  ManagersLejasRoute: ManagersLejasRoute,
  ManagersReemuRoute: ManagersReemuRoute,
  ManagersRexLoiRoute: ManagersRexLoiRoute,
  ManagersShuzaRoute: ManagersShuzaRoute,
}

const ManagersRouteWithChildren = ManagersRoute._addFileChildren(
  ManagersRouteChildren,
)

interface RidersRouteChildren {
  RidersIdRoute: typeof RidersIdRoute
}

const RidersRouteChildren: RidersRouteChildren = {
  RidersIdRoute: RidersIdRoute,
}

const RidersRouteWithChildren =
  RidersRoute._addFileChildren(RidersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRouteWithChildren,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  ManagersRoute: ManagersRouteWithChildren,
  RidersRoute: RidersRouteWithChildren,
  WorldRoute: WorldRoute,
  ApiExportRoute: ApiExportRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
