/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DreamChapterRouteImport } from './routes/dream-chapter'
import { Route as ExtremeSagaRouteImport } from './routes/extreme-saga'
import { Route as FormArchiveRouteImport } from './routes/form-archive'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagersRouteImport } from './routes/managers'
import { Route as RexonanceSagaRouteImport } from './routes/rexonance-saga'
import { Route as RidersRouteImport } from './routes/riders'
import { Route as WorldRouteImport } from './routes/world'
import { Route as ApiArchiveIntelligenceRouteImport } from './routes/api/archive-intelligence'
import { Route as ApiArchiveSearchRouteImport } from './routes/api/archive-search'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as CharactersLunaRouteImport } from './routes/characters/luna'
import { Route as CharactersTerraRouteImport } from './routes/characters/terra'
import { Route as ManagersLejasRouteImport } from './routes/managers/lejas'
import { Route as ManagersOpusRouteImport } from './routes/managers/opus'
import { Route as ManagersReemuRouteImport } from './routes/managers/reemu'
import { Route as ManagersRexLoiRouteImport } from './routes/managers/rex-loi'
import { Route as ManagersShuzaRouteImport } from './routes/managers/shuza'
import { Route as ManagersZeusRouteImport } from './routes/managers/zeus'
import { Route as RidersIdRouteImport } from './routes/riders/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiInternalArchiveAiHealthRouteImport } from './routes/api/internal/archive-ai-health'
import { Route as ApiInternalArchiveAiMaintenanceRouteImport } from './routes/api/internal/archive-ai-maintenance'
import { Route as ApiArchiveAiRequestsRequestIdRouteImport } from './routes/api/archive-ai/requests/$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamChapterRoute = DreamChapterRouteImport.update({
  id: '/dream-chapter',
  path: '/dream-chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtremeSagaRoute = ExtremeSagaRouteImport.update({
  id: '/extreme-saga',
  path: '/extreme-saga',
  getParentRoute: () => rootRouteImport,
} as any)
const FormArchiveRoute = FormArchiveRouteImport.update({
  id: '/form-archive',
  path: '/form-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersRoute = ManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => rootRouteImport,
} as any)
const RexonanceSagaRoute = RexonanceSagaRouteImport.update({
  id: '/rexonance-saga',
  path: '/rexonance-saga',
  getParentRoute: () => rootRouteImport,
} as any)
const RidersRoute = RidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveIntelligenceRoute = ApiArchiveIntelligenceRouteImport.update({
  id: '/api/archive-intelligence',
  path: '/api/archive-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveSearchRoute = ApiArchiveSearchRouteImport.update({
  id: '/api/archive-search',
  path: '/api/archive-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersLunaRoute = CharactersLunaRouteImport.update({
  id: '/luna',
  path: '/luna',
  getParentRoute: () => CharactersRoute,
} as any)
const CharactersTerraRoute = CharactersTerraRouteImport.update({
  id: '/terra',
  path: '/terra',
  getParentRoute: () => CharactersRoute,
} as any)
const ManagersLejasRoute = ManagersLejasRouteImport.update({
  id: '/lejas',
  path: '/lejas',
  getParentRoute: () => ManagersRoute,
} as any)
const ManagersOpusRoute = ManagersOpusRouteImport.update({
  id: '/opus',
  path: '/opus',
  getParentRoute: () => ManagersRoute,
} as any)
const ManagersReemuRoute = ManagersReemuRouteImport.update({
  id: '/reemu',
  path: '/reemu',
  getParentRoute: () => ManagersRoute,
} as any)
const ManagersRexLoiRoute = ManagersRexLoiRouteImport.update({
  id: '/rex-loi',
  path: '/rex-loi',
  getParentRoute: () => ManagersRoute,
} as any)
const ManagersShuzaRoute = ManagersShuzaRouteImport.update({
  id: '/shuza',
  path: '/shuza',
  getParentRoute: () => ManagersRoute,
} as any)
const ManagersZeusRoute = ManagersZeusRouteImport.update({
  id: '/zeus',
  path: '/zeus',
  getParentRoute: () => ManagersRoute,
} as any)
const RidersIdRoute = RidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RidersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalArchiveAiHealthRoute =
  ApiInternalArchiveAiHealthRouteImport.update({
    id: '/api/internal/archive-ai-health',
    path: '/api/internal/archive-ai-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalArchiveAiMaintenanceRoute =
  ApiInternalArchiveAiMaintenanceRouteImport.update({
    id: '/api/internal/archive-ai-maintenance',
    path: '/api/internal/archive-ai-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArchiveAiRequestsRequestIdRoute =
  ApiArchiveAiRequestsRequestIdRouteImport.update({
    id: '/api/archive-ai/requests/$requestId',
    path: '/api/archive-ai/requests/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/download': typeof DownloadRoute
  '/dream-chapter': typeof DreamChapterRoute
  '/extreme-saga': typeof ExtremeSagaRoute
  '/form-archive': typeof FormArchiveRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/managers': typeof ManagersRouteWithChildren
  '/rexonance-saga': typeof RexonanceSagaRoute
  '/riders': typeof RidersRouteWithChildren
  '/world': typeof WorldRoute
  '/api/archive-intelligence': typeof ApiArchiveIntelligenceRoute
  '/api/archive-search': typeof ApiArchiveSearchRoute
  '/api/export': typeof ApiExportRoute
  '/characters/luna': typeof CharactersLunaRoute
  '/characters/terra': typeof CharactersTerraRoute
  '/managers/lejas': typeof ManagersLejasRoute
  '/managers/opus': typeof ManagersOpusRoute
  '/managers/reemu': typeof ManagersReemuRoute
  '/managers/rex-loi': typeof ManagersRexLoiRoute
  '/managers/shuza': typeof ManagersShuzaRoute
  '/managers/zeus': typeof ManagersZeusRoute
  '/riders/$id': typeof RidersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/archive-ai-health': typeof ApiInternalArchiveAiHealthRoute
  '/api/internal/archive-ai-maintenance': typeof ApiInternalArchiveAiMaintenanceRoute
  '/api/archive-ai/requests/$requestId': typeof ApiArchiveAiRequestsRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/download': typeof DownloadRoute
  '/dream-chapter': typeof DreamChapterRoute
  '/extreme-saga': typeof ExtremeSagaRoute
  '/form-archive': typeof FormArchiveRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/managers': typeof ManagersRouteWithChildren
  '/rexonance-saga': typeof RexonanceSagaRoute
  '/riders': typeof RidersRouteWithChildren
  '/world': typeof WorldRoute
  '/api/archive-intelligence': typeof ApiArchiveIntelligenceRoute
  '/api/archive-search': typeof ApiArchiveSearchRoute
  '/api/export': typeof ApiExportRoute
  '/characters/luna': typeof CharactersLunaRoute
  '/characters/terra': typeof CharactersTerraRoute
  '/managers/lejas': typeof ManagersLejasRoute
  '/managers/opus': typeof ManagersOpusRoute
  '/managers/reemu': typeof ManagersReemuRoute
  '/managers/rex-loi': typeof ManagersRexLoiRoute
  '/managers/shuza': typeof ManagersShuzaRoute
  '/managers/zeus': typeof ManagersZeusRoute
  '/riders/$id': typeof RidersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/archive-ai-health': typeof ApiInternalArchiveAiHealthRoute
  '/api/internal/archive-ai-maintenance': typeof ApiInternalArchiveAiMaintenanceRoute
  '/api/archive-ai/requests/$requestId': typeof ApiArchiveAiRequestsRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/download': typeof DownloadRoute
  '/dream-chapter': typeof DreamChapterRoute
  '/extreme-saga': typeof ExtremeSagaRoute
  '/form-archive': typeof FormArchiveRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/managers': typeof ManagersRouteWithChildren
  '/rexonance-saga': typeof RexonanceSagaRoute
  '/riders': typeof RidersRouteWithChildren
  '/world': typeof WorldRoute
  '/api/archive-intelligence': typeof ApiArchiveIntelligenceRoute
  '/api/archive-search': typeof ApiArchiveSearchRoute
  '/api/export': typeof ApiExportRoute
  '/characters/luna': typeof CharactersLunaRoute
  '/characters/terra': typeof CharactersTerraRoute
  '/managers/lejas': typeof ManagersLejasRoute
  '/managers/opus': typeof ManagersOpusRoute
  '/managers/reemu': typeof ManagersReemuRoute
  '/managers/rex-loi': typeof ManagersRexLoiRoute
  '/managers/shuza': typeof ManagersShuzaRoute
  '/managers/zeus': typeof ManagersZeusRoute
  '/riders/$id': typeof RidersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/archive-ai-health': typeof ApiInternalArchiveAiHealthRoute
  '/api/internal/archive-ai-maintenance': typeof ApiInternalArchiveAiMaintenanceRoute
  '/api/archive-ai/requests/$requestId': typeof ApiArchiveAiRequestsRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/download'
    | '/dream-chapter'
    | '/extreme-saga'
    | '/form-archive'
    | '/intelligence'
    | '/login'
    | '/managers'
    | '/rexonance-saga'
    | '/riders'
    | '/world'
    | '/api/archive-intelligence'
    | '/api/archive-search'
    | '/api/export'
    | '/characters/luna'
    | '/characters/terra'
    | '/managers/lejas'
    | '/managers/opus'
    | '/managers/reemu'
    | '/managers/rex-loi'
    | '/managers/shuza'
    | '/managers/zeus'
    | '/riders/$id'
    | '/api/auth/$'
    | '/api/internal/archive-ai-health'
    | '/api/internal/archive-ai-maintenance'
    | '/api/archive-ai/requests/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/download'
    | '/dream-chapter'
    | '/extreme-saga'
    | '/form-archive'
    | '/intelligence'
    | '/login'
    | '/managers'
    | '/rexonance-saga'
    | '/riders'
    | '/world'
    | '/api/archive-intelligence'
    | '/api/archive-search'
    | '/api/export'
    | '/characters/luna'
    | '/characters/terra'
    | '/managers/lejas'
    | '/managers/opus'
    | '/managers/reemu'
    | '/managers/rex-loi'
    | '/managers/shuza'
    | '/managers/zeus'
    | '/riders/$id'
    | '/api/auth/$'
    | '/api/internal/archive-ai-health'
    | '/api/internal/archive-ai-maintenance'
    | '/api/archive-ai/requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/download'
    | '/dream-chapter'
    | '/extreme-saga'
    | '/form-archive'
    | '/intelligence'
    | '/login'
    | '/managers'
    | '/rexonance-saga'
    | '/riders'
    | '/world'
    | '/api/archive-intelligence'
    | '/api/archive-search'
    | '/api/export'
    | '/characters/luna'
    | '/characters/terra'
    | '/managers/lejas'
    | '/managers/opus'
    | '/managers/reemu'
    | '/managers/rex-loi'
    | '/managers/shuza'
    | '/managers/zeus'
    | '/riders/$id'
    | '/api/auth/$'
    | '/api/internal/archive-ai-health'
    | '/api/internal/archive-ai-maintenance'
    | '/api/archive-ai/requests/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  DreamChapterRoute: typeof DreamChapterRoute
  ExtremeSagaRoute: typeof ExtremeSagaRoute
  FormArchiveRoute: typeof FormArchiveRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LoginRoute: typeof LoginRoute
  ManagersRoute: typeof ManagersRouteWithChildren
  RexonanceSagaRoute: typeof RexonanceSagaRoute
  RidersRoute: typeof RidersRouteWithChildren
  WorldRoute: typeof WorldRoute
  ApiArchiveIntelligenceRoute: typeof ApiArchiveIntelligenceRoute
  ApiArchiveSearchRoute: typeof ApiArchiveSearchRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInternalArchiveAiHealthRoute: typeof ApiInternalArchiveAiHealthRoute
  ApiInternalArchiveAiMaintenanceRoute: typeof ApiInternalArchiveAiMaintenanceRoute
  ApiArchiveAiRequestsRequestIdRoute: typeof ApiArchiveAiRequestsRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dream-chapter': {
      id: '/dream-chapter'
      path: '/dream-chapter'
      fullPath: '/dream-chapter'
      preLoaderRoute: typeof DreamChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extreme-saga': {
      id: '/extreme-saga'
      path: '/extreme-saga'
      fullPath: '/extreme-saga'
      preLoaderRoute: typeof ExtremeSagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-archive': {
      id: '/form-archive'
      path: '/form-archive'
      fullPath: '/form-archive'
      preLoaderRoute: typeof FormArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers': {
      id: '/managers'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof ManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rexonance-saga': {
      id: '/rexonance-saga'
      path: '/rexonance-saga'
      fullPath: '/rexonance-saga'
      preLoaderRoute: typeof RexonanceSagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riders': {
      id: '/riders'
      path: '/riders'
      fullPath: '/riders'
      preLoaderRoute: typeof RidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive-intelligence': {
      id: '/api/archive-intelligence'
      path: '/api/archive-intelligence'
      fullPath: '/api/archive-intelligence'
      preLoaderRoute: typeof ApiArchiveIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive-search': {
      id: '/api/archive-search'
      path: '/api/archive-search'
      fullPath: '/api/archive-search'
      preLoaderRoute: typeof ApiArchiveSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/luna': {
      id: '/characters/luna'
      path: '/luna'
      fullPath: '/characters/luna'
      preLoaderRoute: typeof CharactersLunaRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/characters/terra': {
      id: '/characters/terra'
      path: '/terra'
      fullPath: '/characters/terra'
      preLoaderRoute: typeof CharactersTerraRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/managers/lejas': {
      id: '/managers/lejas'
      path: '/lejas'
      fullPath: '/managers/lejas'
      preLoaderRoute: typeof ManagersLejasRouteImport
      parentRoute: typeof ManagersRoute
    }
    '/managers/opus': {
      id: '/managers/opus'
      path: '/opus'
      fullPath: '/managers/opus'
      preLoaderRoute: typeof ManagersOpusRouteImport
      parentRoute: typeof ManagersRoute
    }
    '/managers/reemu': {
      id: '/managers/reemu'
      path: '/reemu'
      fullPath: '/managers/reemu'
      preLoaderRoute: typeof ManagersReemuRouteImport
      parentRoute: typeof ManagersRoute
    }
    '/managers/rex-loi': {
      id: '/managers/rex-loi'
      path: '/rex-loi'
      fullPath: '/managers/rex-loi'
      preLoaderRoute: typeof ManagersRexLoiRouteImport
      parentRoute: typeof ManagersRoute
    }
    '/managers/shuza': {
      id: '/managers/shuza'
      path: '/shuza'
      fullPath: '/managers/shuza'
      preLoaderRoute: typeof ManagersShuzaRouteImport
      parentRoute: typeof ManagersRoute
    }
    '/managers/zeus': {
      id: '/managers/zeus'
      path: '/zeus'
      fullPath: '/managers/zeus'
      preLoaderRoute: typeof ManagersZeusRouteImport
      parentRoute: typeof ManagersRoute
    }
    '/riders/$id': {
      id: '/riders/$id'
      path: '/$id'
      fullPath: '/riders/$id'
      preLoaderRoute: typeof RidersIdRouteImport
      parentRoute: typeof RidersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/archive-ai-health': {
      id: '/api/internal/archive-ai-health'
      path: '/api/internal/archive-ai-health'
      fullPath: '/api/internal/archive-ai-health'
      preLoaderRoute: typeof ApiInternalArchiveAiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/archive-ai-maintenance': {
      id: '/api/internal/archive-ai-maintenance'
      path: '/api/internal/archive-ai-maintenance'
      fullPath: '/api/internal/archive-ai-maintenance'
      preLoaderRoute: typeof ApiInternalArchiveAiMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive-ai/requests/$requestId': {
      id: '/api/archive-ai/requests/$requestId'
      path: '/api/archive-ai/requests/$requestId'
      fullPath: '/api/archive-ai/requests/$requestId'
      preLoaderRoute: typeof ApiArchiveAiRequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CharactersRouteChildren {
  CharactersLunaRoute: typeof CharactersLunaRoute
  CharactersTerraRoute: typeof CharactersTerraRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersLunaRoute: CharactersLunaRoute,
  CharactersTerraRoute: CharactersTerraRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

interface ManagersRouteChildren {
  ManagersLejasRoute: typeof ManagersLejasRoute
  ManagersOpusRoute: typeof ManagersOpusRoute
  ManagersReemuRoute: typeof ManagersReemuRoute
  ManagersRexLoiRoute: typeof ManagersRexLoiRoute
  ManagersShuzaRoute: typeof ManagersShuzaRoute
  ManagersZeusRoute: typeof ManagersZeusRoute
}

const ManagersRouteChildren: ManagersRouteChildren = {
  ManagersLejasRoute: ManagersLejasRoute,
  ManagersOpusRoute: ManagersOpusRoute,
  ManagersReemuRoute: ManagersReemuRoute,
  ManagersRexLoiRoute: ManagersRexLoiRoute,
  ManagersShuzaRoute: ManagersShuzaRoute,
  ManagersZeusRoute: ManagersZeusRoute,
}

const ManagersRouteWithChildren = ManagersRoute._addFileChildren(
  ManagersRouteChildren,
)

interface RidersRouteChildren {
  RidersIdRoute: typeof RidersIdRoute
}

const RidersRouteChildren: RidersRouteChildren = {
  RidersIdRoute: RidersIdRoute,
}

const RidersRouteWithChildren =
  RidersRoute._addFileChildren(RidersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRouteWithChildren,
  DownloadRoute: DownloadRoute,
  DreamChapterRoute: DreamChapterRoute,
  ExtremeSagaRoute: ExtremeSagaRoute,
  FormArchiveRoute: FormArchiveRoute,
  IntelligenceRoute: IntelligenceRoute,
  LoginRoute: LoginRoute,
  ManagersRoute: ManagersRouteWithChildren,
  RexonanceSagaRoute: RexonanceSagaRoute,
  RidersRoute: RidersRouteWithChildren,
  WorldRoute: WorldRoute,
  ApiArchiveIntelligenceRoute: ApiArchiveIntelligenceRoute,
  ApiArchiveSearchRoute: ApiArchiveSearchRoute,
  ApiExportRoute: ApiExportRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInternalArchiveAiHealthRoute: ApiInternalArchiveAiHealthRoute,
  ApiInternalArchiveAiMaintenanceRoute: ApiInternalArchiveAiMaintenanceRoute,
  ApiArchiveAiRequestsRequestIdRoute: ApiArchiveAiRequestsRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
